### ISSUE TITLE
NethVoice: add trunks monitoring alert

### ISSUE THREAD

**Issue by edospadoni** [nethesis/dev#5848]
We need to introduce a new alert to monitor trunks status (*SIP* and *PJSIP*) and show it on **my.nethesis.it** portal.

Alert should contains info about:
- `tech` (SIP or PJSIP)
- `id` (channelid of the trunk)
- `name` (description name)

On **my.nethesis.it** portal all this new alerts should be grouped in the same card, showing in the details the tech and id.

Each 1 minute a script, running on the machines, checks the status and the registration status of the trunk and trigger or resolve an alert. The interval is very low because it is a critical component, if the trunk stops working, after a few seconds the customer can no longer call, to be proactive, the interval must be low.

The priority of the alert is: **Critical**

**Comment by gsanchietti** [comment]
I think a cronjob which runs every minute is not really needed.
First, it is really a bad design: the script takes some seconds to execute sleeps for a while and then is scheduled again.
This is more a daemon beahvior than a cron job one.

I suggest to execute the cronjob every 10 or 5 minutes. Even if asterisk is down, the check is performed after 5 minutes.

The scope of such feature is to inform the administrator about a non-working trunk.

Still, there are cases when the user can be more reactive than any monitoring job:
- is the user is trying to call and line is down
- if the user is expecting an high numbers of incoming call and the phone is not ringing since few minutes

In both cases the user will spend minutes to inform the administrator and, in the meanwhile, the administrator will receive the alert.
Please note that, in case of alert, the administrator can't always do something to fix it.

So I propose to go with the current implementation and increase the cronjob time.

**Comment by gsanchietti** [comment]
It has been pointed out that such feature may raise many unsolicited alerts.
Probably the check should be enabled or disabled using a prop.

Since specs are not clear enough, and we didn't receive enough feedback, I'm closing it for now.
Please reopen it only when everything has been deeply analyzed.
