### ISSUE TITLE
Dante Widgets based on "Traffic by host" empty

### ISSUE THREAD

**Issue by cotosso** [nethesis/dev#6024]
Dante Widgets based on "Traffic by hosts" chart make use of data provided by ntopng.
Everything worked well with version 3.x of ntopng.
From the time we upgraded to ntopng 4.x these widgets are blank and show the messsage "no widget data availlable" 

**Steps to reproduce**

- Install and enable Bandwidth monitor (ntopng)
- Configure dante report adding some widget based on "traffic by host" chart

**Expected behavior**

the widget is correctly showed in the report

**Actual behavior**

Every widget based on "traffic by host" chart show the messsage "no widget data availlable" 

**Components**
NethServer release 7.9.2009 (final)
nethserver-dante-1.0.4-1.ns7.noarch
dante-0.4.5-1.ns7.x86_64
ntopng-data-4.0.200525-9255.noarch
nethserver-ntopng-3.1.2-1.ns7.noarch
ntopng-4.2.201125-11566.x86_64

**Comment by gsanchietti** [comment]
Old implementation comes from nethserver-report: https://github.com/nethesis/nethserver-report/tree/master/root/usr/share/ntopng/scripts/lua

But the script can't be ported because ntopng 4 changed its internal API.
From the [official documentation](https://www.ntop.org/guides/ntopng/api/rest/api_v1.html) I can't see a valid alternative.

By the way, I've created a prototype for `hostrffic-table` (data are not really correct, nor sorted) based on  `custom_data.lua` API.
But since there is no real documentation about what the API does, I've no idea if data are correct:
```perl
#!/usr/bin/perl

use strict;
use warnings;
use JSON;

my $api = 'http://127.0.0.1:3000/lua/rest/v1/get/host/custom_data.lua?ifid=view:all&field_alias=ip,names,local_network_id,bytes.sent,bytes.rcvd';
my $limit = 10;
my $i = 0;
my @data;
my $content = {};
my @rows;

system("/usr/bin/curl -s '$api' | grep '^{' > /tmp/result_ntopng");

my $json;
{
  open my $fh, "<", "/tmp/result_ntopng";
  $json = <$fh>;
  close $fh;
  system("/bin/rm -f /tmp/result_ntopng");
}

if ($json) {
   $content = decode_json($json);
} else {
    exit 1;
}

if (!$content) {
    exit 1;
}

foreach my $host  (@{$content->{'rsp'}}) {
    next if not exists $host->{'local_network_id'};
    push(@rows, $host->{'ip'});
    push(@data, int($host->{'bytes.sent'}), int($host->{'bytes.rcvd'}))
}

print encode_json({
        minerId => "hosttraffic-table",
        type => "table",
        unit => "bytes",
        aggregationType => "snapshot",
        columnHeader => ["sent", "received"],
        anonymizable => JSON::true,
        rowHeader => \@rows,
        rows => \@data
    });
```

I think this is hardly maintainable in the long term. I propose to suppress this widget, see linked PR.

**Comment by gsanchietti** [comment]
In nethserver-testing:
- dante-0.4.5-1.1.g2da9e8b.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
**Test case**
- Update an existing machine
- Verify `hosttraffic-chart-bar` and `hosttraffic-table` are not present inside `/usr/share/dante/miners/`

Please note that old mined data will not be deleted

**Comment by cotosso** [comment]
It works as expected.

**Comment by gsanchietti** [comment]
In nethserver-updates:
dante-0.5.0-1.ns7.x86_64.rpm
